// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, ctx, drawBackground, player;

  canvas = document.getElementById("canvas");

  ctx = canvas.getContext("2d");

  player = {
    x: 500,
    y: 400,
    width: 15,
    height: 15
  };

  drawBackground = function(color) {
    if (color == null) {
      color = "#333";
    }
    ctx.fillStyle = color;
    return ctx.fillRect(0, 0, canvas.width, canvas.height);
  };

  drawBackground();

  console.log("Hello");

}).call(this);
