// Generated by CoffeeScript 1.7.1
(function() {
  var canvas, checkKey, ctx, drawBackground, fps, gameloop, keys, player;

  canvas = document.getElementById("canvas");

  ctx = canvas.getContext("2d");

  fps = 60;

  player = {
    x: 200,
    y: 200,
    width: 20,
    height: 20,
    speed: 3,
    draw: function() {
      ctx.fillStyle = "rgb(0,0,200)";
      return ctx.fillRect(this.x, this.y, this.width, this.height);
    }
  };

  keys = {
    w: {
      code: 87,
      pressed: false
    },
    a: {
      code: 65,
      pressed: false
    },
    s: {
      code: 83,
      pressed: false
    },
    d: {
      code: 68,
      pressed: false
    }
  };

  drawBackground = function(color) {
    if (color == null) {
      color = "#333";
    }
    ctx.fillStyle = color;
    return ctx.fillRect(0, 0, canvas.width, canvas.height);
  };

  checkKey = function(e) {
    var key, _results;
    _results = [];
    for (key in keys) {
      key = keys[key];
      if (e.keyCode === key.code) {
        _results.push(key.pressed = e.type === "keydown");
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  gameloop = function() {
    drawBackground();
    player.draw();
    return setTimeout(gameloop, 1000 / fps);
  };

  gameloop();

  window.onkeydown = checkKey;

  window.onkeyup = checkKey;

}).call(this);
